### ISSUE TITLE
Changed behavior in Storage API for config row detail

### ISSUE THREAD

**Issue by tomasfejfar** [paybyphone/terraform-provider-keboola#44]
We're fixing an issue in our API, where component configuration row detail (call to `/v2/storage/components/{component_id}/configs/{config_id}/rows/{row_id}`) currently returns all rows instead of the exact row. 

We have a release ready (see [related change in Storage API client for PHP and Apiary docs](https://github.com/keboola/storage-api-php-client/pull/216/files#diff-2625016b50d68d922257f74801cac29cR4022)), that fixes this. The endpoint will return only one row based on the supplied id. 

We've checked and most of the calls to this API are from this terraform provider, so we'd like to coordinate the change with a change in your API. Could you change your API accordingly and let us know if the change causes any trouble please?

**Comment by plmwong** [comment]
Thanks for the heads up @tomasfejfar !

I think the PR from @Halama should keep things functioning in the status quo, and then at some point `resourceKeboolaTransformRead` will have to be changed back to calling with the supplied `{row_id}` and just deserialise the result straight to a single `Transformation` instead of an array.

**Comment by plmwong** [comment]
@tomasfejfar I've merged in the pull request, please let me know when you guys roll out the API change.

**Comment by tomasfejfar** [comment]
The API change was merged and will propagate to production in approximately 1 hour.
